Catch null errors
sonata-project/SonataPageBundle pull request #1283
Opened 2021-03-06 11:37 UTC by core23

## Subject

Found some null errors when running `console translation:update`

I am targeting this branch, because this is a patch.

## Changelog

```markdown
### Fixed
- Catch null errors when accessing request
- Catch null errors when loading unknown block
```

2021-03-06 13:40 UTC, VincentLanglet requested changes

2021-03-06 13:40 UTC, VincentLanglet commented on src/Admin/BaseBlockAdmin.php
> +        }
```suggestion
        if (null === $block->getType() || !$this->blockManager->has($block->getType())) {
            return $block;
        }
```

?

2021-03-06 13:40 UTC, VincentLanglet commented on src/Admin/BlockAdmin.php
> +        }
same

2021-03-06 13:40 UTC, VincentLanglet commented on src/Admin/BlockAdmin.php
>          $blockType = $block->getType();
You could use this variable for the previous check

2021-03-06 13:40 UTC, VincentLanglet commented on src/Admin/SharedBlockAdmin.php
> +        }
same

2021-03-06 17:34 UTC, VincentLanglet requested changes

2021-03-06 17:34 UTC, VincentLanglet commented on src/Admin/BaseBlockAdmin.php
> +        }
null === $block->getType() || !$this->blockManager->has($block->getType())

I think you missed your changes

2021-03-06 18:24 UTC, VincentLanglet requested changes

2021-03-06 18:24 UTC, VincentLanglet commented on src/Admin/BaseBlockAdmin.php
> +        }
```suggestion
        if (null === $block->getType() || !$this->blockManager->has($block->getType())) {
            return $block;
        }
```

2021-03-06 18:24 UTC, VincentLanglet commented on src/Admin/BlockAdmin.php
> +        }
```suggestion
        if (null === $block->getType() || !$this->blockManager->has($block->getType())) {
            return;
        }
```

2021-03-06 18:24 UTC, VincentLanglet commented on src/Admin/SharedBlockAdmin.php
> +        }
```suggestion
        if (null === $block->getType() || !$this->blockManager->has($block->getType())) {
            return;
        }
```

2021-03-18 15:59 UTC, VincentLanglet commented on src/Admin/BaseBlockAdmin.php
> +        if (null === $blockType || $this->blockManager->has($blockType)) {
```suggestion
        if (null === $blockType || !$this->blockManager->has($blockType)) {
```

2021-03-18 15:59 UTC, VincentLanglet commented on src/Admin/BlockAdmin.php
> +        if (null === $blockType || $this->blockManager->has($blockType)) {
```suggestion
        if (null === $blockType || !$this->blockManager->has($blockType)) {
```

2021-03-18 15:59 UTC, VincentLanglet commented on src/Admin/SharedBlockAdmin.php
> +        if (null === $blockType || $this->blockManager->has($blockType)) {
```suggestion
        if (null === $blockType || !$this->blockManager->has($blockType)) {
```

2021-03-18 16:01 UTC, core23 commented on src/Admin/BaseBlockAdmin.php
> +        if (null === $blockType || $this->blockManager->has($blockType)) {
Good catch!

2021-03-18 16:03 UTC, VincentLanglet submitted a review, later dismissed

2021-03-18 17:40 UTC, wbloszyk submitted a review, later dismissed

2021-03-18 17:55 UTC, phansys requested changes

2021-03-18 17:55 UTC, phansys commented on src/Admin/PageAdmin.php
> +        if (null === $page || ($page && $page->getParent()) || ($page && !$page->getId())) {
```suggestion
        if (null === $page || ($page && $page->getParent()) || ($page && null === $page->getId())) {
```

2021-03-18 17:55 UTC, phansys commented on src/Admin/PageAdmin.php
> +        if (null !== $page && !$page->getId()) {
```suggestion
        if (null !== $page && null === $page->getId()) {
```

2021-03-18 20:11 UTC, phansys approved these changes

2021-03-18 20:16 UTC, jordisala1991 approved these changes

2021-03-18 20:31 UTC, merged

2021-03-18 20:31 UTC, phansys commented
Thank you @core23!