There is a direct dependency on the jms serializer bundle in api_form.xml
sonata-project/SonataPageBundle pull request #1305
Opened 2021-04-20 12:22 UTC by 4c0n

## Subject

There is a direct dependency on the jms serializer bundle in api_form.xml, so I moved the bundle from the dev dependencies into the dependencies section.

The dependency is there for all environments and will cause issues if the `jms_serializer.metadata_factory` service id does not exist.

I am targeting this branch, because it is the current version.

## Changelog

Moved jms serializer bundle dependency from dev dependencies to the regular dependencies section.

2021-04-20 12:23 UTC, 4c0n commented
https://github.com/sonata-project/SonataPageBundle/blob/fed26c06856de8d6b1161d0f23001db7b8377e2b/src/Resources/config/api_form.xml#L6

2021-04-20 12:45 UTC, VincentLanglet approved these changes

2021-04-20 16:01 UTC, franmomu commented
`api_form.xml` only gets loaded when 

https://github.com/sonata-project/SonataPageBundle/blob/fed26c06856de8d6b1161d0f23001db7b8377e2b/src/DependencyInjection/SonataPageExtension.php#L70-L75

I think we could also add a check for `JMSSerializerBundle` instead of move it to the `require` section.

2021-04-21 08:38 UTC, 4c0n commented
@franmomu That makes sense, hope this behavior is well documented somewhere, as it isn't great when services in a bundle "magically" appear or disappear based on the configuration of another bundle. Actually for a long time having one bundle depend on another bundle was considered bad practice, maybe that has changed?

Another approach would be to depend on the components that the other bundle uses and define the services in this bundle. That way there is no need to depend on the other bundle for its services.
Let me know what you think :)

2021-04-21 11:31 UTC, core23 requested changes
The api is an optional dependency:
https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/DependencyInjection/SonataPageExtension.php#L70-L75

2021-04-21 11:35 UTC, core23 commented
> @franmomu That makes sense, hope this behavior is well documented somewhere, as it isn't great when services in a bundle "magically" appear or disappear based on the configuration of another bundle. Actually for a long time having one bundle depend on another bundle was considered bad practice, maybe that has changed?

:+1: 

IMHO the best way is a separate bundle which adds an API layer to this bundle, but it would require some more refactoring. Using this `magic` thing is the current solution across all our bundles.

2021-04-21 11:36 UTC, franmomu commented
It should be documented for sure.

About dependencies, in an ideal world, we could maybe remove the API part and create a package with the code and a bundle maybe that integrates the API part to this bundle, but that would be a lot of work and maintenance.

The thing about components, IMO, the problem I see is that usually those services depend on another services, so you would have to create (and maintain) several services that don't really add value, instead of using it. And also sometimes this services are configurable and you want to configure them from the original bundle.

2021-04-27 11:53 UTC, core23 submitted a review, later dismissed

2021-04-27 12:01 UTC, VincentLanglet submitted a review, later dismissed

2021-04-27 12:02 UTC, VincentLanglet commented
tests need to be fixed

2021-04-27 20:30 UTC, jordisala1991 approved these changes

2021-04-27 20:43 UTC, VincentLanglet approved these changes

2021-04-27 20:43 UTC, VincentLanglet commented
Please review @core23 :)

2021-04-28 09:06 UTC, core23 approved these changes

2021-04-28 09:08 UTC, merged

2021-04-28 09:08 UTC, greg0ire commented
Thanks @4c0n