Add support for CacheBundle 3 and PHP 8
sonata-project/SonataPageBundle pull request #1341
Opened 2021-08-21 08:49 UTC by VincentLanglet

## Subject

Finishing https://github.com/sonata-project/SonataPageBundle/pull/1304 and https://github.com/sonata-project/SonataPageBundle/pull/1274.

I am targeting this branch, because we decided it was acceptable on this branch.
https://github.com/sonata-project/SonataPageBundle/pull/1304#issuecomment-825586356

## Changelog

```markdown
### Added
- Support for `SonataCacheBundle` v3.
- Support for PHP 8.
- Some return type hint to `BlockEsiCache`, `BlockJsCache` and `BlockSsiCache`.

### Changed
- `BlockEsiCache::__construct` signature
- `BlockSsiCache::__construct` signature

### Removed
- Support for `SonataCacheBundle` v2.
- Support for `SonataCache` v1.
```

2021-08-21 09:32 UTC, VincentLanglet commented
Dev-kit PR: https://github.com/sonata-project/dev-kit/pull/1636

2021-08-21 10:25 UTC, core23 approved these changes

2021-08-22 16:06 UTC, phansys requested changes

2021-08-22 16:06 UTC, phansys commented on UPGRADE-3.x.md
> +`SonataCacheBundle` was upgrade from `2.x` to `3.x`. Because of the change in the `CacheAdapterInterface`,
```suggestion
`SonataCacheBundle` was upgraded from `2.x` to `3.x`. Because of the change in the `CacheAdapterInterface`,
```

2021-08-22 16:06 UTC, phansys commented on UPGRADE-3.x.md
> +- Some methods of `BlockEsiCache`, `BlockJsCache` and `BlockSsiCache` have now return type hints.
IMO, we should use "type hints" for the cases where these hints are provided through docblocks, and "type declarations" for the cases where these hints are really checked by the PHP interpreter.

2021-08-22 16:06 UTC, phansys commented on UPGRADE-3.x.md
> +If you override any of these class make sure you are explicitly declaring your dependency with
```suggestion
If you override any of these classes, make sure you are explicitly declaring your dependency with
```

2021-08-22 16:06 UTC, phansys commented on UPGRADE-3.x.md
> +`sonata-project/cache-bundle` to your `composer.json` in order to avoid unwanted upgrades.
```suggestion
`sonata-project/cache-bundle` in your `composer.json` in order to avoid unwanted upgrades.
```

2021-08-22 16:10 UTC, VincentLanglet commented
Done @phansys

2021-08-22 16:56 UTC, phansys approved these changes

2021-08-22 17:03 UTC, merged